name: myapp
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase: ^9.0.3
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.6.1
  supabase_flutter: ^2.8.3
  image_picker: ^1.1.2
  html: ^0.15.5
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
